services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-server
    ports:
      - '9000:9000' # API 端口
      - '9001:9001' # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data # 文件映射地址
    command: server /data --console-address ":9001"
    restart: always

  pageindex-api:
    build:
      context: .
      dockerfile: pageindex.Dockerfile
    container_name: pageindex-api
    ports:
      - "9090:9090"
    environment:
      - OPENAI_API_BASE=https://api.deepseek.com/v1
      - OPENAI_API_KEY=${DEEPSEEK_API_KEY}

    volumes:
      - ./pageindex_data:/app/output # 存放向量索引和解析结果
    restart: always

  # 自动创建 bucket 的可选工具容器
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/documents;
      /usr/bin/mc anonymous set public myminio/documents;
      exit 0;
      "
